### ISSUE TITLE
Suggestion: Reducing Number of Clicks in Common Use Workflow

### ISSUE THREAD

**Issue by volomike** [Alanaktion/phproject#237]
Although I do see that this tool shows lots of promise, I would like to suggest some changes in how this operates. After awhile, and in my opinion, this tool became cumbersome to use due to the number of clicks I had to do to accomplish common tasks such as:

1. Creating users in particular roles.
2. Putting users in groups.
3. Creating a new project.
4. Assigning a group to a project.
5. Creating child tasks for a project.

It was also strange in that when you create a new child task inside a project, it doesn't appear unless you exit the project and come back in again. Imagine trying to add 15 tasks to a project all at once. Also, when you complete the Add Task form, the usual place to return is the page with the tasks there (including the one you just created), and one doesn't need to click to get back to that view again. Unfortunately, though, that's not how this works. I get to a project and don't see a clear way intuitively where I am to create child tasks for a project. Once editing a project, it's not a form field like the comments field that's already present, and not a button in the upper right. Instead, I guessed that I should click the Child Tasks tab, and was surprised that I guessed properly. I then saw a New Task button. I clicked it to create a child task, but then it returned back to the project edit page, and I had to click the Child Tasks tab again to see child tasks, and even then my new task wasn't there until I exited the project and went back in to edit again, and then clicked Child Tasks.

My suggestion is that you take this back to a storyboard with a tool like Balsamiq Mockups, and iron out a workflow with less clicks for a very common series of tasks like I suggested in the 5 steps above. Then, build again.

Some similar project management systems you might consider testing and having their page layout and workflow inspire you could be:

* http://lighthouseapp.com/
* https://www.proofhub.com/

Also, does this use a templating engine? Does that slow this down? I've built quite a few LAMP apps and haven't seen something this slow. However, I use PHP as the templating engine, rather than using a templating engine -- it seems faster that way, and is easier to code, none-the-less.

Here's how I use PHP as a templating engine:

* Anywhere I can cache data that either never changes once logged in, or rarely changes, I do it. I use serialize() and write it to a file in some cases, or write it as raw HTML to a file in other cases. I also think about cases where the data might need to be cached per user, or per group of users, or per anyone using the application, or per session, or per logged-in usage of the application (not necessarily a session), and so on.

* I use an MVC system, but my view templates are straight PHP with stuff like this inside:

```
<div>some sample html</div>
<?= $view->USERNAME ?>
<div>some more html</div>
<?php if ($view->LOGGED_IN): ?>
<div>show logged in text</div>
<?php else: ?>
<div>show not logged in text</div>
<?php endif; ?>
```

The reason for ALL CAPS on the variables is so that they are found more easily inside the HTML templates. The reason for the $view object is because it's nothing more than:

```
$view = (object) array();
$view->USERNAME = 'test';
$view->LOGGED_IN = TRUE;
```

And then that lets me use `print_r($view);` to dump the contents out for debugging. I can also iterate through the object properties to scrub the HTML for XSS and CSRF before display.

Hope this helps this project.

**Comment by Alanaktion** [comment]
User management is very rare compared with project/task creation and tracking, so that's not really optimized. If you can recommend a better way of doing it, I'd be fine with changing it; I'm not particularly happy with the way it's done now.

Project/task hierarchy is simplified in the interface where it's intended to be simplified, the Taskboard. Currently you need to have projects in sprints for them to display on the taskboard, but that will give you something close to the interface you're looking for. The main interface works well for what it's designed for, which is a large number of standalone tasks with many collaborators.

While this *does* use a templating system, I don't see any performance issues arising from it's usage. The templates are converted to raw PHP on the first page load, and then cached permanently, so there's no performance advantage to making them flat PHP files from the beginning, and using straight PHP can encourage poor development behavior since you're no longer restricted in what goes in views, so I won't be changing that.

Additionally, I am already caching most things that don't change after login. Make sure your `tmp/cache/` directory is writable by your web server, or that `APC` is installed if you want a simple in-memory cache. If you want to customize the caching environment further (use memcached, etc.), see the [F3 caching documentation](https://fatfreeframework.com/optimization#CacheEngine). I don't experience any page speed issues, my average page load time on this project is around 120ms, with many pages loading in under 80ms, which is very fast for the complexity of the project.
