### ISSUE TITLE
Wrong URL in password reset email

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#238]
BUG

When the user resets his password, the link generated for the email contains an additional [dot] before the TLD (see screenshot). This bug does not apply to any other email generated.
![pw-reset-servernotfound](https://cloud.githubusercontent.com/assets/18327444/17182645/801cef2c-5424-11e6-96f2-ce5bf64fed5b.JPG)

Are there different url-functions for users who are loged in vs. users loged out? I tried to fix this myself but I could not figure out where/how site.url is generated. There doesn't seem to be a config variable in the database or any config.ini I could find (please enlighten me :) ).

**Comment by Alanaktion** [comment]
By default, `site.url` is generated in `index.php`, currently on line 18. If you use emails on a cron job though, you'll need to set it in either `config.ini` or the `config` database table.

I'm not sure how you would get two dots in the hostname, since it gets it from `$_SERVER['SERVER_NAME']` by default, this is a very weird bug.

**Comment by BerChill** [comment]
Alright, so I did some excessive testing and I could narrow it down to the following:

When the part before `.tld` exceeds 23 characters not countng `http://` (testet with various combinations of letters, numbers and dots) an additional `.` is added before the tld. It doesn't matter how long the tld is.

This is really strange especially since it works fine with all the other notifications. I reckon `{{ @site.url }}` is not to blame for this since this bug only applies to the password reset notification.

Any ideas?

**Comment by Alanaktion** [comment]
So this was really confusing to trace down, but it's sort of caused by @ikkez's commit 9991fc2. Lines 36-39 switch a single leading `.` to two `.` characters after the email is split into several lines for sending over SMTP, so a hostname of that length perfectly matches the line splitting length.
Technically, that behavior is correct, but some email servers don't correctly remove the second `.` as they should according to the spec, so I think I'm going to try to re-implement the `quoted_printable_encode` function in a way that always encodes `.` to `=2E`.
