### ISSUE TITLE
Broken Mail Links on Due Issues Notifications

### ISSUE THREAD

**Issue by BerChill** [Alanaktion/phproject#253]
BUG-NOTIFICATIONS

OBSERVED BEHAVIOR
The mail that informs users about due notifications contains broken issue links and a broken "view dashboard" link. Upon clicking the link, nothing is happening.
![dueissues](https://cloud.githubusercontent.com/assets/18327444/19201186/e4ff836a-8ccc-11e6-80ab-87ac7967a99f.JPG)

EXPECTED BEHAVIOR
Issue LInks and the "view dashboard" link in notification mails are clickable and the user is redirected to the issue page in the standard browser

**Comment by Alanaktion** [comment]
This isn't currently documented, but since the site detects it's domain from the HTTP Host header normally, cron jobs aren't able to automatically generate the URLs. Adding `site.url` with the complete address to your Phproject root (e.g. `http://example.com/phproject/`) to either config.ini or the config database table should correct the links.
I'll add this to the documentation, and also consider making the installer auto-set this value.

**Comment by Alanaktion** [comment]
I've created #254 to track auto-setting this value from the installer.
