### ISSUE TITLE
Limit access to groups

### ISSUE THREAD

**Issue by deonvisser** [Alanaktion/phproject#292]
Hi

Is it possible to limit access to only certain projects depending in which group the user is.

I have multiple projects but do not want all users to see all projects.

Hint: Maybe some docs on your website explaining what groups are all about?

Thanks

**Comment by Alanaktion** [comment]
Group-level access isn't currently implemented, but could complement #45.

Currently, groups are primarily used as a way to filter backlog/taskboard items, and to assign a single item to multiple users. Assigning an item to a group will notify all the users of that group, and it will display on each user's dashboard. You can also select groups in the Browse page filters and see all items created by/assigned to users within that group.

**Comment by deonvisser** [comment]
Thank you Alan

**Comment by justme636** [comment]
Hi there! Because I work in a big company I do need an access control for projects and tasks; as long as this is not possible I can't use the software at all. I could cope with any other missing feature being implemented in the future but access control is quite necessary for me right now. If access control doesn't come up soon, I'll need to switch over to an other solution. That would be a pity because I actually like phprojects for simplicity :(

**Comment by formicum** [comment]
Hi, 
is there a chance, that Group_Level Access will be implemented soon?
It's a no go for us, if we need different phproject instances for different projects/customers. It would be a huge thing, to have one phproject-installation for all you different projects, customers and devs.

Best regards, GB

**Comment by justme636** [comment]
Hi Alan!
I do respect your efforts to provide phproject as free and open source software and I guess you work on it in your (rare) free time without any payment. Thank you at that point! But apparently, there are some more users considering access control as a crucial point. I think several people can’t use phproject properly as long as there is no access control. By now, I’m not sure if waiting for access control is worth it - I’ve been waiting for that feature since February and neither came a response here since March 2017 nor I got an answer to my e-mail I had sent to you one month ago. I don’t want to set pressure on you but could you please give us a clue whether access control will be implemented soon (and waiting is worth it)? Something like „Yes, it will be implemented in the next weeks“ would do. Thank you once again!

**Comment by Alanaktion** [comment]
I've been considering implementing this for a long time now, but I'm not sure how it would work best. If we can come up with a good way of implementing it that's intuitive to use, I'm very willing to work on it, but so far I haven't come up with a good way to limit access to things with the way it's currently structured. If any of you have ideas on how you would like to see this work, please add a comment! I'd like to make something that meets everyone's needs here, without limiting the flexibility of how things work now.

I'd love input from @MrGecco and @windhamdavid from the related #45 as well.

**Comment by justme636** [comment]
Thank you for that quick response :) I’m happy to see that this issue is not forgotten. Unfortunately, I can’t support with in-depth coding skills but maybe that helps: For me as an end user, regulation of access (=visibility?) to an items by a group the user assigned to could be a first solution - maybe just provisional? I know that mechanism is not very flexible and capable of errors (like changes of assignments in sub/parent items…) but it would provide such a feature at all until some smart guys who are much more talented with such things than I am can help to develop a more flexible solution :D But anyway, I’m glad that you are still working on it and so I'll keep following that issue.

**Comment by Citydampf** [comment]
i changed (added) this in controller/issues.php for show, edit and search issues only to author and owner.

public function index($f3)
    {
        $issues = new \Model\Issue\Detail;
        $helper = \Helper\Dashboard::instance();
        $ownerString = implode(",", $helper->getOwnerIds());
        $userId = $f3->get("user.id"); 
        // Get filter
        $args = $f3->get("GET");
        list($filter, $filter_str) = $this->_buildFilter();
        $filter_str = "(owner_id IN (". $ownerString .") OR author_id = ".$userId.") AND " . $filter_str;
...

------------------------------------------------------------------------------
    public function single($f3, $params)
    {
        $issue = new \Model\Issue\Detail;
        $issue->load(array("id=?", $params["id"]));
        $user = $f3->get("user_obj");
$helper = \Helper\Dashboard::instance();
$ownerArray = $helper->getOwnerIds();

        if (!$issue->id || ($issue->deleted_date && !($user->role == 'admin' || $user->rank >= \Model\User::RANK_MANAGER || $issue->author_id == $user->id)) || !(in_array($issue->owner_id,$ownerArray) || $issue->author_id == $user->id)) 
        {
         //  if ($user->role != 'admin')
           {  
            $f3->error(404);
            return;
          }
        }
...

------------------------------------------

    public function edit($f3, $params)
    {
        //$issue = new \Model\Issue;
        $issue = new \Model\Issue\Detail;
        $issue->load($params["id"]);
        $user = $f3->get("user_obj");
    $helper = \Helper\Dashboard::instance();
    $ownerArray = $helper->getOwnerIds();

        if (!$issue->id || !(in_array($issue->owner_id,$ownerArray) || $issue->author_id == $user->id )) {
         // if ($user->role != 'admin')
           {
            $f3->error(404, "Issue does not exist");
            return;
          }
        }
...

and in function search after checking args[closed] 

        $helper = \Helper\Dashboard::instance();
        $ownerString = implode(",", $helper->getOwnerIds());
        $userId = $f3->get("user.id");
        $where[0] .= " AND (owner_id IN (". $ownerString .") OR author_id = ".$userId.")";

**Comment by GelLiNN** [comment]
I like what Citydampf has done, and with a little UI development, another table in the DB, and some changes to the install pattern this can be done pretty easily.

Here's what I'm thinking:

- another table called user_permissions which has a row for each user, and a column for each project.
- each time a new project is created, a new column gets added to this table
- each time a new user is created, a new row gets added to this table
- each user would have a true/false value for each project column and this would allow/deny access to different projects
- super admin would have direct access through the Admin dashboard to select which users have access to which projects by directly editing this table
- a new permissions controller would need to be implemented to accomplish the above
- the install operation would need to add this table to its operations
- the filter code added above would need to be added to the issues controller, except using the user_permissions table instead of author/etc as above

Tell me what you think @Alanaktion

**Comment by GelLiNN** [comment]
Already got started on this but I need some direction on the show/search/index filtering part in the way that I need.  I have already finished the preliminary UI changes I talked about
https://github.com/Building-Intellect/BI-projects/commit/f6fe1214077ae598128d80728a78c533a06b335b

**Comment by GelLiNN** [comment]
I have successfully implemented this fully now with https://github.com/Building-Intellect/BI-projects/commit/f639231114b4b12aeeb3b93003e6f26d0879ca85

**Comment by tadKeys** [comment]
Hi GelLiNN,

are you planning to submit pull requests to feed your changes back to phproject?

Thanks,
Stephan

**Comment by GelLiNN** [comment]
I can but it would be quite different than the current offering of phproject.  I have totally customized lots of different aspects of the application to fit my specific business needs.  But If its needed I can pull apart some of the changes I made for group-level access and submit a PR.

**Comment by tadKeys** [comment]
This would be really great!

**Comment by kralynch** [comment]
Submitted a PR to restrict issues based on user's group without having to modify the database.
https://github.com/Alanaktion/phproject/pull/393

It allows access to all issues for admin user. All other users see issues that are assigned to themselves and their group.
