### ISSUE TITLE
can't upload pdf files to a project

### ISSUE THREAD

**Issue by jonium** [Alanaktion/phproject#411]
Hello,
I can upload files of other extensions but pdf.
Is there a list of allowed extensions?

**Comment by Alanaktion** [comment]
There are some file types that are blocked, but PDFs are definitely allowed. You are most likely being limited by file size rather than type, PHP by default limits files to only 2 MB on most installations. Check your `upload_max_filesize` and `post_max_size` settings in php.ini, and also check the file size setting limit in the site configuration.

If you're using nginx, there is also a limit on request body size there that can be adjusted with the `client_max_body_size` value as shown in the `nginx-example.conf` configuration file.

**Comment by jonium** [comment]
The Pdf file size is 4 Mb and I see that other pdf files were uploaded.
I'm using Apache, upload_max_filesize and post_max_size are 64M.
I thought it maybe modsecurity, disabled it and same situation, no errors neither in any log and at screen

**Comment by Alanaktion** [comment]
There is a limit set in the Phproject configuration, you can adjust it from the Administration > Configuration page, in the Advanced tab.

**Comment by jonium** [comment]
Thanks, 
trying to change it I get "No attribute specified."

**Comment by jonium** [comment]
I change it from the db
