### ISSUE TITLE
Private issues

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/phproject#45]
Add the ability to create private issues. Issues marked as private will only be visible to the creator, assignee, and any watchers. Privacy settings should be inherited by all descendents below the issue that is initially marked as private.

**Comment by MrGecco** [comment]
Yesterday I tried phproject and have to say I really like it - exactly what I was looking for. Great job guys.
Sadly, we can't use due to the missing function.
Just wanted to say thank you for the great product, you're on the right way. And encourage you to implement this feature for v2.0. Thank you.

**Comment by windhamdavid** [comment]
Same issue as @MrGecco, otherwise spot on. This summer I'll dig in with some pull requests to try and help out. Thanks 👍🏻

**Comment by justme636** [comment]
Hi there! Because I work in a big company, I do need an access control for projects and tasks; as long as this is not possible I can't use the software at all. I could cope with any other missing feature being implemented in the future but access control is quite necessary for me right now. If access control doesn't come up soon, I'll need to switch over to an other solution. That would be a pity because I actually like phprojects for simplicity :(

**Comment by Alanaktion** [comment]
I'm merging this with #292, since they make sense to implement together. I'd love more feedback there on how you'd like to see this work!
